# Generated by Django 4.1 on 2023-08-26 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTwo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=60)),
                ('level', models.IntegerField()),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
